#!/bin/bash

cd `dirname $0`/../

# start upload-service

upload-service/start

# NPM global mode path
export NPM_CONFIG_PREFIX=~/.npm-global
export PATH=$PATH:$(npm get prefix)/bin
cloudcmd --port 8887 --root docs --no-open --no-contact &

yarn start --port 3000
