#!/bin/bash

cd `dirname $0`/../

# start upload-service
node upload-service/index.js --port 8888 --root ./docs/ &

# NPM global mode path
export NPM_CONFIG_PREFIX=~/.npm-global
export PATH=$PATH:$(npm get prefix)/bin
cloudcmd --port 8887 --root docs --no-open --no-contact &

# start editor
yarn --cwd ./editor start &

# start production Docusaurus
yarn serve --port 8585 &

# start live Docusaurus
docusaurus start --port 3000
